/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import baseDatos.DatabaseConnection;
import codigo.Departamento;
import codigo.Sucursal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yorvi
 */
public class Departamentos extends javax.swing.JFrame {

    /**
     * Creates new form Sucursales
     */
    public Departamentos() {
        initComponents();
        setTitle("Gestión de Sucursales");
        setLocationRelativeTo(null);
        setResizable(false);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_agregarDP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_DEP = new javax.swing.JTable();
        B_Editar = new javax.swing.JButton();
        B_Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        B_agregarDP.setText("Agregar Departamento");
        B_agregarDP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_agregarDP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_agregarDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregarDPActionPerformed(evt);
            }
        });

        jButton1.setText("Volver Al Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        T_DEP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Correo", "Telefono", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(T_DEP);

        B_Editar.setText("Editar Departamento");
        B_Editar.setToolTipText("");
        B_Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditarActionPerformed(evt);
            }
        });

        B_Eliminar.setText("Eliminar Departamento");
        B_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestión de Departamentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_agregarDP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_agregarDP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_agregarDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregarDPActionPerformed
        // TODO add your handling code here:
        // Solicitar el código del departamento
    String codDepartamentoStr = JOptionPane.showInputDialog(this, "Ingrese el código del departamento:");
    if (codDepartamentoStr == null || codDepartamentoStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El código de departamento no puede estar vacío.");
        return;
    }

    // Solicitar el nombre del departamento
    String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del departamento:");
    if (nombre == null || nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre del departamento no puede estar vacío.");
        return;
    }

    // Solicitar la descripción del departamento
    String descripcion = JOptionPane.showInputDialog(this, "Ingrese la descripción del departamento:");
    if (descripcion == null || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La descripción del departamento no puede estar vacía.");
        return;
    }

    int codDepartamento;
    try {
        codDepartamento = Integer.parseInt(codDepartamentoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El código de departamento debe ser un número.");
        return;
    }

    // Crear la conexión y objeto de la clase Departamento
    DatabaseConnection conexion = new DatabaseConnection();
    conexion.conectarJ();

    Departamento departamento = new Departamento(conexion.getConnection());

    // Llamar al método para agregar el departamento
    boolean success = departamento.agregarDepartamento(codDepartamento, nombre, descripcion);

    if (success) {
        JOptionPane.showMessageDialog(this, "Departamento agregado exitosamente.");

        // Aquí puedes agregar código para actualizar la tabla si es necesario
        departamento.llenar(T_DEP);  
    } else {
        JOptionPane.showMessageDialog(this, "Error al agregar el departamento.");
    }
    }//GEN-LAST:event_B_agregarDPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
       
       menu.setVisible(true);
       
       setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditarActionPerformed
        // TODO add your handling code here:
        editarDepartamento();
    }//GEN-LAST:event_B_EditarActionPerformed

    private void B_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EliminarActionPerformed
        // TODO add your handling code here:
        eliminarDepartamento();
    }//GEN-LAST:event_B_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Departamentos().setVisible(true);
            }
        });
    }
    
    public void llenarTabla() {
    DatabaseConnection conexion = new DatabaseConnection();
    conexion.conectarJ();
    
    Departamento DEP = new Departamento(conexion.getConnection());
    DefaultTableModel model = DEP.obtenerDepartamentos();
    
    if (model.getRowCount() > 0) {
        T_DEP.setModel(model);
        System.out.println("Datos añadidos a la tabla.");
    } else {
        System.out.println("No se encontraron datos para mostrar.");
    }
}
    
    private void editarDepartamento() {
    int selectedRow = T_DEP.getSelectedRow();
    if (selectedRow >= 0) {
        DefaultTableModel model = (DefaultTableModel) T_DEP.getModel();
        int codDepartamento = (int) model.getValueAt(selectedRow, 0);
        String nombreDepartamento = (String) model.getValueAt(selectedRow, 1);
        String descripDepartamento = (String) model.getValueAt(selectedRow, 2);

        boolean continuar = true;
        while (continuar) {
            String[] options = {"Nombre", "Descripción", "Cancelar"};
            int choice = JOptionPane.showOptionDialog(this,
                "¿Qué campo desea actualizar?",
                "Seleccionar Campo",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]);

            switch (choice) {
                case 0:
                    nombreDepartamento = JOptionPane.showInputDialog(this, "Nombre del departamento:", nombreDepartamento);
                    break;
                case 1:
                    descripDepartamento = JOptionPane.showInputDialog(this, "Descripción del departamento:", descripDepartamento);
                    break;
                case 2:
                    continuar = false;
                    break;
                default:
                    continuar = false;
                    break;
            }

            if (choice != 2 && choice != JOptionPane.CLOSED_OPTION) {
                int more = JOptionPane.showConfirmDialog(this, "¿Desea actualizar otro campo?", "Continuar", JOptionPane.YES_NO_OPTION);
                continuar = (more == JOptionPane.YES_OPTION);
            } else {
                continuar = false;
            }
        }

        // Actualizar la base de datos
        DatabaseConnection conexion = new DatabaseConnection();
        conexion.conectarJ();
        Departamento departamentoDAO = new Departamento(conexion.getConnection());
        departamentoDAO.actualizarDepartamento(codDepartamento, nombreDepartamento, descripDepartamento);
        conexion.desconectar();

        // Volver a llenar la tabla con los datos actualizados
        llenarTabla();
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un departamento para editar.");
    }
}
    private void eliminarDepartamento() {
    int selectedRow = T_DEP.getSelectedRow();
    if (selectedRow >= 0) {
        DefaultTableModel model = (DefaultTableModel) T_DEP.getModel();
        int codDepartamento = (int) model.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar el departamento con código " + codDepartamento + "?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Eliminar el departamento de la base de datos
            DatabaseConnection conexion = new DatabaseConnection();
            conexion.conectarJ();
            Departamento departamentoDAO = new Departamento(conexion.getConnection());
            departamentoDAO.eliminarDepartamento(codDepartamento);
            conexion.desconectar();

            // Volver a llenar la tabla con los datos actualizados
            llenarTabla();
            JOptionPane.showMessageDialog(this, "Departamento eliminado exitosamente.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un departamento para eliminar.");
    }
}



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Editar;
    private javax.swing.JButton B_Eliminar;
    private javax.swing.JButton B_agregarDP;
    private javax.swing.JTable T_DEP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
